# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NUMBER.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 382)
        #self.return_2 = QtWidgets.QPushButton(Form)
        #self.return_2.setGeometry(QtCore.QRect(560, 350, 75, 23))
        #self.return_2.setObjectName("return_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(150, 210, 211, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.enter = QtWidgets.QPushButton(Form)
        self.enter.setGeometry(QtCore.QRect(410, 210, 75, 23))
        self.enter.setObjectName("enter")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(220, 130, 221, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        #self.return_2.setText(_translate("Form", "返回"))
        self.enter.setText(_translate("Form", "輸入"))
        self.label.setText(_translate("Form", "請輸入想挑戰的接龍的次數"))
