# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'START.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_start(object):
    def setupUi(self, start):
        start.setObjectName("start")
        start.resize(649, 383)
        self.startButton = QtWidgets.QPushButton(start)
        self.startButton.setGeometry(QtCore.QRect(250, 240, 151, 51))
        self.startButton.setObjectName("startButton")

        self.retranslateUi(start)
        QtCore.QMetaObject.connectSlotsByName(start)

    def retranslateUi(self, start):
        _translate = QtCore.QCoreApplication.translate
        start.setWindowTitle(_translate("start", "Form"))
        self.startButton.setText(_translate("start", "開始"))
